### ISSUE TITLE
max link idle reach, close the underlying net.Conn 怎么解决

### ISSUE THREAD

**Issue by maoguoxu** [ooclab/otunnel#17]
time="07/03 11:01:10" level=warning msg="link is stopped already" from=link id=0
time="07/03 11:01:19" level=warning msg="ping failed" error=timeout from=link id=0 idle=1m2.000863288s
time="07/03 11:01:19" level=error msg="max link idle reach, close the underlying net.Conn" from=link id=0 idle=1m2.000863288s
panic: close of nil channel

goroutine 49 [running]:
github.com/ooclab/otunnel/vendor/github.com/ooclab/es/link.(*Link).Stop(0xc42022e0a0, 0xc42016aea8, 0x1)
	/Users/gwind/go/src/github.com/ooclab/otunnel/vendor/github.com/ooclab/es/link/link.go:181 +0xd7
github.com/ooclab/otunnel/vendor/github.com/ooclab/es/link.(*Link).keepalive(0xc42022e0a0, 0x2, 0xc42017c000)
	/Users/gwind/go/src/github.com/ooclab/otunnel/vendor/github.com/ooclab/es/link/link.go:244 +0x6c5
github.com/ooclab/otunnel/vendor/github.com/ooclab/es/link.newLink.func1(0xc42022e0a0)
	/Users/gwind/go/src/github.com/ooclab/otunnel/vendor/github.com/ooclab/es/link/link.go:125 +0x32
created by github.com/ooclab/otunnel/vendor/github.com/ooclab/es/link.newLink
	/Users/gwind/go/src/github.com/ooclab/otunnel/vendor/github.com/ooclab/es/link/link.go:124 +0x6a1
nohup: ignoring input

**Comment by gwind** [comment]
It is a known issues, would be fixed when I have time 😢
